### ISSUE TITLE
Prometheus or Grafana doesn't see exported Gunicorn metrics

### ISSUE THREAD

**Issue by S0mbre** [blueswen/gunicorn-monitoring#1]
What I did
---

Adding everything as per the workflow suggested, I have the following `docker-compose.yml`:

```yml
statsd: # statsd-exporter
    image: prom/statsd-exporter:latest
    container_name: statsd
    restart: unless-stopped
    expose:
      - 9125
      - 9102
    volumes:
      - ./statsd.conf:/statsd/statsd.conf
    command:
      - --statsd.mapping-config=/statsd/statsd.conf

prometheus: # prometheus
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    command: "--config.file=/etc/prometheus/prometheus.yml"
    expose:
      - 9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

grafana: # grafana
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    user: "472"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    
fhback: # FastAPI app
    # some params ...
    expose:
      - 8000
    command: sh -c "gunicorn --workers 6 --timeout 60 --bind 0.0.0.0:8000 --statsd-host=statsd:9125 --statsd-prefix=fhback.app -k uvicorn.workers.UvicornWorker main:app"
```

`prometheus.yml`:

```yml
global:
  scrape_interval: 15s
  scrape_timeout: 7s
  evaluation_interval: 15s
  external_labels:
    monitor: "app"

alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 8s
    api_version: v2
    static_configs:
    - targets: []    

scrape_configs:
  - job_name: "prometheus"
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "app"
    scrape_interval: 10s
    dns_sd_configs:
      - names: ["app"]  
        port: 8000
        type: A
        refresh_interval: 5s

  - job_name: "statsd"
    static_configs:
      - targets: ["statsd:9102"]
```

The only change from the original repo is `app name`: mine is `fhback.app`: `gunicorn --workers 6 --timeout 60 --bind 0.0.0.0:8000 --statsd-host=statsd:9125 --statsd-prefix=fhback.app ...`

The `statsd.conf` was copied from the repo without changes. The Grafana dashboard is added also as-is from the repo example. 

Problem
---

However, with all the services running normally and no errors in logs, Grafana doesn't see any Gunicorn data arriving:

![001](https://github.com/blueswen/gunicorn-monitoring/assets/5337394/12f09e52-59c7-420a-81d6-45a71bc9a449)

![002](https://github.com/blueswen/gunicorn-monitoring/assets/5337394/668dfae6-80cf-469f-bdde-9f27a5c7e7af)

![003](https://github.com/blueswen/gunicorn-monitoring/assets/5337394/81818254-0454-4569-ad7a-12fe71a6546c)
